/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Noto Sans Arabic"', 'Outfit', 'sans-serif'],
        'display-lg': ['Outfit', '"Noto Sans Arabic"'],
        'display-lg-mobile': ['Outfit', '"Noto Sans Arabic"'],
        'headline-lg': ['Outfit', '"Noto Sans Arabic"'],
        'headline-md': ['Outfit', '"Noto Sans Arabic"'],
        'label-sm': ['Outfit', '"Noto Sans Arabic"'],
        'label-md': ['Outfit', '"Noto Sans Arabic"'],
        'body-lg': ['Outfit', '"Noto Sans Arabic"'],
        'body-md': ['Outfit', '"Noto Sans Arabic"'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
      spacing: {
        unit: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        gutter: '16px',
        lg: '24px',
        xl: '40px',
        xxl: '64px',
        'margin-mobile': '20px',
        'margin-tablet': '32px',
      },
      colors: {
        surface: '#0e141c',
        'surface-dim': '#0e141c',
        'surface-bright': '#343943',
        'surface-tint': '#4cd7f6',
        'surface-variant': '#30353e',
        'surface-container-lowest': '#090e17',
        'surface-container-low': '#171c24',
        'surface-container': '#1b2029',
        'surface-container-high': '#252a33',
        'surface-container-highest': '#30353e',
        'canvas-deep': '#02050C',
        'canvas-elevated': '#0A0F1A',
        background: '#0e141c',
        primary: '#4cd7f6',
        'primary-fixed': '#acedff',
        'primary-fixed-dim': '#4cd7f6',
        'primary-container': '#06b6d4',
        'inverse-primary': '#00687a',
        'on-primary': '#003640',
        'on-primary-fixed': '#001f26',
        'on-primary-fixed-variant': '#004e5c',
        'on-primary-container': '#00424f',
        secondary: '#d2bbff',
        'secondary-container': '#6001d1',
        'secondary-fixed': '#eaddff',
        'secondary-fixed-dim': '#d2bbff',
        'on-secondary': '#3f008e',
        'on-secondary-container': '#c9aeff',
        'on-secondary-fixed': '#25005a',
        'on-secondary-fixed-variant': '#5a00c6',
        tertiary: '#ffb873',
        'tertiary-container': '#e89337',
        'tertiary-fixed': '#ffdcbf',
        'tertiary-fixed-dim': '#ffb873',
        'on-tertiary': '#4b2800',
        'on-tertiary-container': '#5b3200',
        'on-tertiary-fixed': '#2d1600',
        'on-tertiary-fixed-variant': '#6a3b00',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'on-surface': '#dee2ef',
        'on-surface-variant': '#bcc9cd',
        'on-background': '#dee2ef',
        'inverse-surface': '#dee2ef',
        'inverse-on-surface': '#2b313a',
        outline: '#869397',
        'outline-variant': '#3d494c',
        'text-primary': '#FFFFFF',
        'text-secondary': '#E2E8F0',
        'accent-violet': '#7C3AED',
        'accent-cyan': '#06B6D4',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
