export interface VoiceDefinition {
  id: string;
  name: string;
  avatar: string;
  language: string;
  accent: string;
  gender: "male" | "female" | "neutral";
  category: "narration" | "characters" | "conversational" | "news" | "epic" | "social" | "calm" | "arabic";
  tag: "NARR" | "CHAT" | "CHAR" | "NEWS" | "EPIC" | "SOC" | "CALM" | "ARABIC";
  tagColor: "green" | "blue" | "red" | "orange" | "amber" | "purple" | "teal";
  sampleUrl: string;
  provider: "gemini" | "elevenlabs" | "wavespeed" | "custom";
  geminiVoiceId?: string;
  isCloned?: boolean;
}

export const VOICE_CATALOG: VoiceDefinition[] = [
  // ─── 1. Narration Voices ──────────────────────────────────────────
  {
    id: "johnny-kid",
    name: "Johnny Kid",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    language: "English",
    accent: "English · Calm Narrator",
    gender: "male",
    category: "narration",
    tag: "NARR",
    tagColor: "green",
    sampleUrl: "/api/voice-sample?voice=Charon&lang=en",
    provider: "gemini",
    geminiVoiceId: "Charon",
  },
  {
    id: "addison-2",
    name: "Addison 2.0",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    language: "English",
    accent: "English · Australian",
    gender: "female",
    category: "narration",
    tag: "NARR",
    tagColor: "green",
    sampleUrl: "/api/voice-sample?voice=Aoede&lang=en",
    provider: "gemini",
    geminiVoiceId: "Aoede",
  },
  {
    id: "ellen",
    name: "Ellen",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    language: "English",
    accent: "English · Direct Serious",
    gender: "female",
    category: "narration",
    tag: "NARR",
    tagColor: "green",
    sampleUrl: "/api/voice-sample?voice=Kore&lang=en",
    provider: "gemini",
    geminiVoiceId: "Kore",
  },
  {
    id: "juniper",
    name: "Juniper",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    language: "English",
    accent: "English · Grounded Pro",
    gender: "female",
    category: "narration",
    tag: "NARR",
    tagColor: "green",
    sampleUrl: "/api/voice-sample?voice=Zephyr&lang=en",
    provider: "gemini",
    geminiVoiceId: "Zephyr",
  },
  {
    id: "theodore-hq",
    name: "Theodore HQ",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    language: "English",
    accent: "English · Serene",
    gender: "male",
    category: "narration",
    tag: "NARR",
    tagColor: "green",
    sampleUrl: "/api/voice-sample?voice=Orus&lang=en",
    provider: "gemini",
    geminiVoiceId: "Orus",
  },

  // ─── 2. Conversational Voices ─────────────────────────────────────
  {
    id: "aria",
    name: "Aria",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    language: "English",
    accent: "English · American",
    gender: "female",
    category: "conversational",
    tag: "CHAT",
    tagColor: "blue",
    sampleUrl: "/api/voice-sample?voice=Leda&lang=en",
    provider: "gemini",
    geminiVoiceId: "Leda",
  },
  {
    id: "sarah",
    name: "Sarah",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    language: "English",
    accent: "English · American",
    gender: "female",
    category: "conversational",
    tag: "CHAT",
    tagColor: "blue",
    sampleUrl: "/api/voice-sample?voice=Autonoe&lang=en",
    provider: "gemini",
    geminiVoiceId: "Autonoe",
  },
  {
    id: "laura",
    name: "Laura",
    avatar: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80",
    language: "English",
    accent: "English · American",
    gender: "female",
    category: "conversational",
    tag: "CHAT",
    tagColor: "blue",
    sampleUrl: "/api/voice-sample?voice=Callirrhoe&lang=en",
    provider: "gemini",
    geminiVoiceId: "Callirrhoe",
  },
  {
    id: "charlotte",
    name: "Charlotte",
    avatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80",
    language: "English",
    accent: "English · British",
    gender: "female",
    category: "conversational",
    tag: "CHAT",
    tagColor: "blue",
    sampleUrl: "/api/voice-sample?voice=Despina&lang=en",
    provider: "gemini",
    geminiVoiceId: "Despina",
  },
  {
    id: "alice",
    name: "Alice",
    avatar: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=150&auto=format&fit=crop&q=80",
    language: "English",
    accent: "English · British",
    gender: "female",
    category: "conversational",
    tag: "CHAT",
    tagColor: "blue",
    sampleUrl: "/api/voice-sample?voice=Erinome&lang=en",
    provider: "gemini",
    geminiVoiceId: "Erinome",
  },
  {
    id: "jessica",
    name: "Jessica",
    avatar: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80",
    language: "English",
    accent: "English · American",
    gender: "female",
    category: "conversational",
    tag: "CHAT",
    tagColor: "blue",
    sampleUrl: "/api/voice-sample?voice=Laomedeia&lang=en",
    provider: "gemini",
    geminiVoiceId: "Laomedeia",
  },
  {
    id: "chris",
    name: "Chris",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
    language: "English",
    accent: "English · American",
    gender: "male",
    category: "conversational",
    tag: "CHAT",
    tagColor: "blue",
    sampleUrl: "/api/voice-sample?voice=Puck&lang=en",
    provider: "gemini",
    geminiVoiceId: "Puck",
  },
  {
    id: "anika",
    name: "Anika",
    avatar: "https://images.unsplash.com/photo-1548142813-c348350df52b?w=150&auto=format&fit=crop&q=80",
    language: "English",
    accent: "English · Friendly",
    gender: "female",
    category: "conversational",
    tag: "CHAT",
    tagColor: "blue",
    sampleUrl: "/api/voice-sample?voice=Achernar&lang=en",
    provider: "gemini",
    geminiVoiceId: "Achernar",
  },
  {
    id: "tiffany",
    name: "Tiffany",
    avatar: "https://images.unsplash.com/photo-1546961329-78bef0414d7c?w=150&auto=format&fit=crop&q=80",
    language: "English",
    accent: "English · Welcoming",
    gender: "female",
    category: "conversational",
    tag: "CHAT",
    tagColor: "blue",
    sampleUrl: "/api/voice-sample?voice=Schedar&lang=en",
    provider: "gemini",
    geminiVoiceId: "Schedar",
  },
  {
    id: "sam",
    name: "Sam",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    language: "English",
    accent: "English · Support",
    gender: "male",
    category: "conversational",
    tag: "CHAT",
    tagColor: "blue",
    sampleUrl: "/api/voice-sample?voice=Iapetus&lang=en",
    provider: "gemini",
    geminiVoiceId: "Iapetus",
  },
  {
    id: "mark",
    name: "Mark",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80",
    language: "English",
    accent: "English · Casual Relaxed",
    gender: "male",
    category: "conversational",
    tag: "CHAT",
    tagColor: "blue",
    sampleUrl: "/api/voice-sample?voice=Umbriel&lang=en",
    provider: "gemini",
    geminiVoiceId: "Umbriel",
  },
  {
    id: "mark-nat",
    name: "Mark (Nat.)",
    avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80",
    language: "English",
    accent: "English · Natural",
    gender: "male",
    category: "conversational",
    tag: "CHAT",
    tagColor: "blue",
    sampleUrl: "/api/voice-sample?voice=Achird&lang=en",
    provider: "gemini",
    geminiVoiceId: "Achird",
  },
  {
    id: "blondie",
    name: "Blondie",
    avatar: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=150&auto=format&fit=crop&q=80",
    language: "English",
    accent: "English · Conversational",
    gender: "female",
    category: "conversational",
    tag: "CHAT",
    tagColor: "blue",
    sampleUrl: "/api/voice-sample?voice=Pulcherrima&lang=en",
    provider: "gemini",
    geminiVoiceId: "Pulcherrima",
  },
  {
    id: "lucy",
    name: "Lucy",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    language: "English",
    accent: "English · Fresh Casual",
    gender: "female",
    category: "conversational",
    tag: "CHAT",
    tagColor: "blue",
    sampleUrl: "/api/voice-sample?voice=Vindemiatrix&lang=en",
    provider: "gemini",
    geminiVoiceId: "Vindemiatrix",
  },
  {
    id: "jessica-ab",
    name: "Jessica A.B.",
    avatar: "https://images.unsplash.com/photo-1534751516642-a171edd2521d?w=150&auto=format&fit=crop&q=80",
    language: "English",
    accent: "English · Chatty",
    gender: "female",
    category: "conversational",
    tag: "CHAT",
    tagColor: "blue",
    sampleUrl: "/api/voice-sample?voice=Sulafat&lang=en",
    provider: "gemini",
    geminiVoiceId: "Sulafat",
  },
  {
    id: "priyanka",
    name: "Priyanka",
    avatar: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80",
    language: "Multilingual",
    accent: "Multilingual · Calm Neutral",
    gender: "female",
    category: "calm",
    tag: "CHAT",
    tagColor: "blue",
    sampleUrl: "/api/voice-sample?voice=Gacrux&lang=en",
    provider: "gemini",
    geminiVoiceId: "Gacrux",
  },
  {
    id: "adeline",
    name: "Adeline",
    avatar: "https://images.unsplash.com/photo-1524502397800-2eeaad7c3fe5?w=150&auto=format&fit=crop&q=80",
    language: "English",
    accent: "English · Feminine",
    gender: "female",
    category: "conversational",
    tag: "CHAT",
    tagColor: "blue",
    sampleUrl: "/api/voice-sample?voice=Leda&lang=en",
    provider: "gemini",
    geminiVoiceId: "Leda",
  },
  {
    id: "lily",
    name: "Lily",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    language: "English",
    accent: "English · British",
    gender: "female",
    category: "conversational",
    tag: "CHAT",
    tagColor: "blue",
    sampleUrl: "/api/voice-sample?voice=Despina&lang=en",
    provider: "gemini",
    geminiVoiceId: "Despina",
  },

  // ─── 3. Characters & Expressive Voices ───────────────────────────
  {
    id: "roger",
    name: "Roger",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
    language: "English",
    accent: "English · American",
    gender: "male",
    category: "characters",
    tag: "CHAR",
    tagColor: "red",
    sampleUrl: "/api/voice-sample?voice=Fenrir&lang=en",
    provider: "gemini",
    geminiVoiceId: "Fenrir",
  },
  {
    id: "fenrir-epic",
    name: "Fenrir Titan",
    avatar: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=150&auto=format&fit=crop&q=80",
    language: "English",
    accent: "English · Deep Movie Trailer",
    gender: "male",
    category: "epic",
    tag: "EPIC",
    tagColor: "amber",
    sampleUrl: "/api/voice-sample?voice=Alnilam&lang=en",
    provider: "gemini",
    geminiVoiceId: "Alnilam",
  },

  // ─── 4. Arabic Master Voices (أصوات عربية فائقة الدقة) ───────────
  {
    id: "tariq-ar",
    name: "طارق (Tariq)",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    language: "Arabic",
    accent: "عربي · فصحى وثائقي وإخباري",
    gender: "male",
    category: "arabic",
    tag: "ARABIC",
    tagColor: "purple",
    sampleUrl: "/api/voice-sample?voice=Charon&lang=ar",
    provider: "gemini",
    geminiVoiceId: "Charon",
  },
  {
    id: "layla-ar",
    name: "ليلى (Layla)",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    language: "Arabic",
    accent: "عربي · دافئة وسلسة للإعلانات",
    gender: "female",
    category: "arabic",
    tag: "ARABIC",
    tagColor: "purple",
    sampleUrl: "/api/voice-sample?voice=Zephyr&lang=ar",
    provider: "gemini",
    geminiVoiceId: "Zephyr",
  },
  {
    id: "zayd-ar",
    name: "زيد (Zayd)",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    language: "Arabic",
    accent: "عربي · خليجي حماسي واجتماعي",
    gender: "male",
    category: "arabic",
    tag: "ARABIC",
    tagColor: "purple",
    sampleUrl: "/api/voice-sample?voice=Orus&lang=ar",
    provider: "gemini",
    geminiVoiceId: "Orus",
  },
  {
    id: "maryam-ar",
    name: "مريم (Maryam)",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    language: "Arabic",
    accent: "عربي · قصصي وإرشادي مريح",
    gender: "female",
    category: "arabic",
    tag: "ARABIC",
    tagColor: "purple",
    sampleUrl: "/api/voice-sample?voice=Kore&lang=ar",
    provider: "gemini",
    geminiVoiceId: "Kore",
  },
  {
    id: "omar-ar",
    name: "عمر (Omar)",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
    language: "Arabic",
    accent: "عربي · واثق ورسمي للمشاريع",
    gender: "male",
    category: "arabic",
    tag: "ARABIC",
    tagColor: "purple",
    sampleUrl: "/api/voice-sample?voice=Iapetus&lang=ar",
    provider: "gemini",
    geminiVoiceId: "Iapetus",
  },
  {
    id: "hamed-ar",
    name: "حامد (Hamed)",
    avatar: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=150&auto=format&fit=crop&q=80",
    language: "Arabic",
    accent: "عربي · عميق وسينمائي",
    gender: "male",
    category: "arabic",
    tag: "ARABIC",
    tagColor: "purple",
    sampleUrl: "/api/voice-sample?voice=Enceladus&lang=ar",
    provider: "gemini",
    geminiVoiceId: "Enceladus",
  },
];
