// ============================================================
// Hollywood AI Studio — Mock Async Job Engine
// ============================================================
// Simulates real AI model calls with realistic timing and
// failure rates. Replace with real service adapters for
// production.
// ============================================================
// API_INTEGRATION_POINT: Every function here should be replaced
// with real API calls in the service adapter layer.
// ============================================================

import { MODEL_ROUTING, resolveModel } from './model-routing';

const delay = (ms: number) => new Promise<void>(r => setTimeout(r, ms));
const randomBetween = (min: number, max: number) => Math.random() * (max - min) + min;
const failRate = 0.05; // 5% simulated failure rate
const shouldFail = () => Math.random() < failRate;

export interface MockJobResult<T> {
  success: boolean;
  data?: T;
  error?: string;
  model: string;
  provider: string;
  durationMs: number;
  usedFallback: boolean;
}

// ── Script Generation ──────────────────────────────────────
export async function mockGenerateScript(
  prompt: string,
  preset: string
): Promise<MockJobResult<string>> {
  const model = resolveModel('scriptWriting');
  const start = Date.now();
  await delay(randomBetween(1500, 3000));

  if (shouldFail()) {
    // Try fallback
    const fallback = MODEL_ROUTING.scriptWriting.fallback;
    if (fallback) {
      await delay(randomBetween(1000, 2000));
      return {
        success: true,
        data: `[Generated by ${fallback}] Script for "${prompt}" in ${preset} style...`,
        model: fallback,
        provider: MODEL_ROUTING.scriptWriting.provider,
        durationMs: Date.now() - start,
        usedFallback: true,
      };
    }
    return {
      success: false,
      error: `${model} failed and no fallback available`,
      model,
      provider: MODEL_ROUTING.scriptWriting.provider,
      durationMs: Date.now() - start,
      usedFallback: false,
    };
  }

  return {
    success: true,
    data: `[Generated by ${model}] Script for "${prompt}" in ${preset} style...`,
    model,
    provider: MODEL_ROUTING.scriptWriting.provider,
    durationMs: Date.now() - start,
    usedFallback: false,
  };
}

// ── Image Generation ───────────────────────────────────────
export async function mockGenerateImage(
  prompt: string
): Promise<MockJobResult<string>> {
  const model = resolveModel('imageGenPrimary');
  const start = Date.now();
  await delay(randomBetween(3000, 6000));

  if (shouldFail()) {
    const fallback = MODEL_ROUTING.imageGenPrimary.fallback;
    if (fallback) {
      await delay(randomBetween(2000, 4000));
      return {
        success: true,
        data: '/mock/generated-image-fallback.png',
        model: fallback,
        provider: 'Fallback',
        durationMs: Date.now() - start,
        usedFallback: true,
      };
    }
  }

  return {
    success: true,
    data: '/mock/generated-image.png',
    model,
    provider: MODEL_ROUTING.imageGenPrimary.provider,
    durationMs: Date.now() - start,
    usedFallback: false,
  };
}

// ── Video Generation ───────────────────────────────────────
export async function mockGenerateVideo(
  sceneId: string,
  model?: string
): Promise<MockJobResult<string>> {
  const selectedModel = model || resolveModel('videoGenPrimary');
  const start = Date.now();

  // Video generation takes longer
  await delay(randomBetween(8000, 15000));

  if (shouldFail()) {
    const fallbackModel = MODEL_ROUTING.videoGenSecondary.primary;
    await delay(randomBetween(5000, 10000));
    return {
      success: true,
      data: '/mock/generated-video-fallback.mp4',
      model: fallbackModel,
      provider: MODEL_ROUTING.videoGenSecondary.provider,
      durationMs: Date.now() - start,
      usedFallback: true,
    };
  }

  return {
    success: true,
    data: '/mock/generated-video.mp4',
    model: selectedModel,
    provider: MODEL_ROUTING.videoGenPrimary.provider,
    durationMs: Date.now() - start,
    usedFallback: false,
  };
}

// ── TTS Preview ────────────────────────────────────────────
export async function mockPreviewTTS(
  text: string,
  voiceId: string
): Promise<MockJobResult<string>> {
  const model = resolveModel('ttsPrimary');
  const start = Date.now();
  await delay(randomBetween(1000, 2500));

  return {
    success: true,
    data: '/mock/tts-preview.mp3',
    model,
    provider: MODEL_ROUTING.ttsPrimary.provider,
    durationMs: Date.now() - start,
    usedFallback: false,
  };
}

// ── Voice Cloning ──────────────────────────────────────────
export async function mockCloneVoice(
  name: string
): Promise<MockJobResult<{ id: string; name: string }>> {
  const model = resolveModel('voiceCloning');
  const start = Date.now();
  await delay(randomBetween(15000, 30000)); // PVC takes a while

  return {
    success: true,
    data: { id: `cloned-${Date.now()}`, name },
    model,
    provider: MODEL_ROUTING.voiceCloning.provider,
    durationMs: Date.now() - start,
    usedFallback: false,
  };
}

// ── Render ─────────────────────────────────────────────────
export function mockRenderProgress(
  onProgress: (progress: number, status: string) => void,
  onComplete: () => void,
  onError?: (error: string) => void
): () => void {
  let progress = 0;
  const interval = setInterval(() => {
    progress += randomBetween(3, 12);
    if (progress >= 100) {
      progress = 100;
      clearInterval(interval);
      onProgress(100, 'complete');
      onComplete();
      return;
    }
    const status = progress > 75 ? 'encoding' : 'processing';
    onProgress(progress, status);
  }, 2000);

  // Return cancel function
  return () => {
    clearInterval(interval);
    onError?.('Cancelled by user');
  };
}
