import { NextRequest, NextResponse } from "next/server";
import { auth } from "@clerk/nextjs/server";

export const dynamic = "force-dynamic";

export async function POST(req: NextRequest) {
  try {
    const { userId } = await auth();
    if (!userId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { messages, selectedVideoModel, selectedImageModel } = await req.json().catch(() => ({}));
    if (!messages || !Array.isArray(messages)) {
      return NextResponse.json({ error: "Invalid messages format" }, { status: 400 });
    }

    const apiKey =
      process.env.GOOGLE_AI_API_KEY ||
      process.env.GOOGLE_API_KEY ||
      process.env.GEMINI_API_KEY ||
      process.env.GOOGLE_GENAI_API_KEY;

    if (!apiKey) {
      return NextResponse.json(
        { error: "Google API Key is not configured on the server." },
        { status: 500 }
      );
    }

    // Forward the incoming request's cookie so protected same-origin media
    // (e.g. /api/media/...) can be fetched with the user's auth session.
    const forwardedCookie = req.headers.get("cookie") || "";

    // Format chat history for Google Gemini API
    const contents = [];
    for (const m of messages) {
      const parts: any[] = [];
      let loadedRefs = 0;
      let failedRefs = 0;

      // Download and attach reference images if present.
      // Attach media from BOTH user (uploaded refs) and agent (previously
      // generated assets) — otherwise the agent has no memory of what it
      // produced last turn and will deny generating anything.
      const urlsToFetch: string[] = [];
      if (m.assetUrl) urlsToFetch.push(m.assetUrl);
      if (m.assetUrls && Array.isArray(m.assetUrls)) {
        for (const url of m.assetUrls) {
          if (url && !urlsToFetch.includes(url)) {
            urlsToFetch.push(url);
          }
        }
      }

      for (const url of urlsToFetch) {
        try {
          let targetUrl = url;
          const isSameOrigin = targetUrl.startsWith("/");
          if (isSameOrigin) {
            targetUrl = `${req.nextUrl.origin}${targetUrl}`;
          }

          const imgRes = await fetch(targetUrl, {
            headers: isSameOrigin && forwardedCookie ? { cookie: forwardedCookie } : {},
          });

          if (imgRes.ok) {
            const buffer = await imgRes.arrayBuffer();
            const base64 = Buffer.from(buffer).toString("base64");
            const contentType = imgRes.headers.get("content-type") || "image/jpeg";
            // Skip anything that isn't clearly an image (Gemini rejects other types silently)
            if (contentType.startsWith("image/") || contentType.startsWith("video/")) {
              parts.push({
                inlineData: { mimeType: contentType, data: base64 },
              });
              loadedRefs += 1;
            } else {
              failedRefs += 1;
              console.error(`[cinema-flow chat] reference URL returned non-media content-type: ${contentType} · ${targetUrl}`);
            }
          } else {
            failedRefs += 1;
            console.error(`[cinema-flow chat] reference fetch failed ${imgRes.status} for ${targetUrl}`);
          }
        } catch (e) {
          failedRefs += 1;
          console.error("[cinema-flow chat] reference fetch threw:", e);
        }
      }

      // Add the text part LAST so image data appears before the accompanying prompt.
      // Prepend explicit system-visible notes so the model:
      //  · never claims "I don't see images" when references are attached,
      //  · never denies producing an image when it did in a previous turn.
      let textForModel = m.text || "";
      if (urlsToFetch.length > 0) {
        if (loadedRefs > 0) {
          const label = m.sender === "user"
            ? `[Attached ${loadedRefs} reference image${loadedRefs > 1 ? "s" : ""} from the user — describe/use them directly. You CAN see them.]`
            : `[The following ${loadedRefs} image${loadedRefs > 1 ? "s were" : " was"} generated by YOU (Cinema Flow) in this turn and is now in the user's gallery. Acknowledge you made it, describe it, and iterate on it if asked.]`;
          textForModel = `${label}\n\n${textForModel}`;
        } else if (failedRefs > 0) {
          textForModel = `[Note: ${failedRefs} attached media item${failedRefs > 1 ? "s" : ""} could not be loaded server-side. If the user asks, tell them honestly the upload failed and ask them to re-upload.]\n\n${textForModel}`;
        }
      }
      parts.push({ text: textForModel });

      contents.push({
        role: m.sender === "user" ? "user" : "model",
        parts,
      });
    }

    const systemInstruction = {
      parts: [
        {
          text: `You are Cinema Flow, the creative agent of Saad Studio.

===============================================================
YOUR DEFAULT MODE IS CONVERSATION
===============================================================
By default, you TALK — you brainstorm, refine ideas, suggest details,
ask clarifying questions, propose scenes and shots. You do NOT
generate anything until the user gives an explicit execute command.

Even if the user says things like "make a sunset image", "draw a
palace", "create a video", "صمّم لي مشهد", "اصنع صورة",
"ولّد لي" — treat these as CREATIVE DISCUSSION. Reply with
questions or suggestions ("سأصنع لك ذلك — تريد الأسلوب سينمائي أم
واقعي؟ نسبة أفقية أم عمودية؟ اضغط 'نفذ' عندما تكون جاهزًا").

Keep replies short (1–3 sentences). Match the user's language and
dialect (Arabic by default).

===============================================================
EXECUTE-ONLY TRIGGER WORDS
===============================================================
You emit a tool call ONLY when the user's latest message contains
one of these EXPLICIT execute commands (case-insensitive, may appear
alone or in a short phrase):

  Arabic:  نفذ · نفّذ · ابدأ · أبدأ · تنفيذ · شغّل · شغل · هيا
  English: execute · go · start · run · do it · proceed

If none of these words appears in the user's LAST message, you MUST
reply conversationally — never emit a trigger.

===============================================================
WHEN YOU DO EXECUTE — WHAT YOU SAY = WHAT WILL HAPPEN
===============================================================
Every triggered turn produces EXACTLY ONE image OR ONE video.
Never promise multiple shots, variants, or a series. If the user
wants more, they'll say "نفذ" again for the next one.

===============================================================
YOU REMEMBER WHAT YOU GENERATED
===============================================================
When a previous assistant message shows a "[The following image was
generated by YOU ...]" note with an image attached, that IS your
prior output. NEVER say "we haven't generated anything yet" —
acknowledge it exists, describe what's in it, and offer to iterate
(new angle, different lighting, next shot in the series, etc.).

===============================================================
REFERENCE IMAGES — YOU CAN SEE THEM
===============================================================
You are a MULTIMODAL model. When reference images are attached to a
user message, they appear as inlineData BEFORE the user's text and
you CAN see them directly — describe them, name what's in them,
match their colors/lighting/composition when helping the user.

NEVER say "I can't see images" or "I don't see the way humans do".
If the user asks "did you see the reference?" — describe what you
see in it briefly.

If a message begins with "[Note: reference could not be loaded]" —
tell the user honestly that the upload failed on the server and ask
them to re-upload. Otherwise assume every attached image is visible
to you.

When generating, references are passed to the image/video model too —
you don't paste URLs. Just describe the transformation ("same
character, new angle", "same lighting, dusk").

===============================================================
TOOL CALL FORMAT
===============================================================
When (and only when) the user's last message contained an explicit
execute command, respond with ONE LINE ONLY — no narration, no
explanation, just the trigger:

  IMAGE_GEN: <the full visual prompt built from the whole conversation,
             in the user's language, preserving every detail they gave>

  VIDEO_GEN: <same rules; silent video>

  VIDEO_WITH_VOICEOVER_GEN: <visual prompt> | <voiceover script>

Build the prompt from the ENTIRE conversation context so the earlier
brainstorming is reflected in the generated asset.`,
        },
      ],
    };

    // Query Gemini
    const model = "gemini-2.5-flash";
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;

    const res = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents,
        systemInstruction,
        generationConfig: {
          maxOutputTokens: 800,
        },
      }),
    });

    if (!res.ok) {
      const errText = await res.text();
      console.error("[cinema-flow chat] API error:", errText);
      throw new Error(`Google API returned status ${res.status}`);
    }

    const data = await res.json();
    const candidateText = data.candidates?.[0]?.content?.parts?.[0]?.text || "";

    return NextResponse.json({ text: candidateText.trim() });
  } catch (err: any) {
    console.error("[cinema-flow chat] error:", err);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
