"use client";

import React, { useState, useEffect, useCallback, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  DndContext,
  DragEndEvent,
  DragOverEvent,
  DragStartEvent,
  PointerSensor,
  useSensor,
  useSensors,
  DragOverlay,
  closestCenter,
  useDroppable,
} from "@dnd-kit/core";
import {
  SortableContext,
  useSortable,
  verticalListSortingStrategy,
  arrayMove,
} from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import {
  Sparkles,
  GripVertical,
  Trash2,
  Pencil,
  ImageIcon,
  Video,
  Plus,
  ChevronDown,
  Save,
  CheckCircle2,
  Eye,
  LayoutTemplate,
  Grid3x3,
  Quote,
  Star,
  X,
  Upload,
  AlertTriangle,
  Layers,
  Play,
  RefreshCw,
} from "lucide-react";

// â”€â”€â”€ TYPES â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

export type BlockType =
  | "HERO"
  | "FEATURE_CARD"
  | "DISCOVER_GRID"
  | "TESTIMONIAL";

export interface LayoutBlock {
  id: string;
  type: BlockType;
  title: string;
  subtitle: string;
  mediaUrl: string;
  isVideo: boolean;
  badge?: string;
  ctaHref?: string;
  ctaLabel?: string;
  trailerUrl?: string;
  accentColor?: string;
  youtubeUrl?: string;
}

// â”€â”€â”€ BLOCK TEMPLATES (palette) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

const BLOCK_TEMPLATES: {
  type: BlockType;
  label: string;
  description: string;
  icon: React.ElementType;
  color: string;
  defaults: Omit<LayoutBlock, "id">;
}[] = [
  {
    type: "HERO",
    label: "Hero Section",
    description: "Full-width video or image hero with headline",
    icon: Sparkles,
    color: "from-violet-500/20 to-purple-600/10 border-violet-500/30",
    defaults: {
      type: "HERO",
      title: "The Ultimate AI Creative Studio",
      subtitle: "Generate breathtaking videos, images & audio â€” all in one place.",
      mediaUrl: "https://picsum.photos/seed/hero/1280/600",
      isVideo: false,
      badge: "NEW",
      ctaHref: "/dash",
      ctaLabel: "Try Now",
      trailerUrl: "",
      accentColor: "#8b5cf6",
      youtubeUrl: "",
    },
  },
  {
    type: "FEATURE_CARD",
    label: "Feature Card",
    description: "Highlight a platform feature with icon + text",
    icon: LayoutTemplate,
    color: "from-blue-500/20 to-cyan-600/10 border-blue-500/30",
    defaults: {
      type: "FEATURE_CARD",
      title: "AI Video Generation",
      subtitle: "Create cinematic videos with Kling 3.0 and Seedance models.",
      mediaUrl: "https://picsum.photos/seed/feature/600/400",
      isVideo: false,
    },
  },
  {
    type: "DISCOVER_GRID",
    label: "Discover Grid Item",
    description: "A card displayed in the Discover page masonry grid",
    icon: Grid3x3,
    color: "from-emerald-500/20 to-teal-600/10 border-emerald-500/30",
    defaults: {
      type: "DISCOVER_GRID",
      title: "Futuristic City â€” Kling 3.0",
      subtitle: "Generated by @alex.smith",
      mediaUrl: "https://picsum.photos/seed/discover/600/800",
      isVideo: false,
    },
  },
  {
    type: "TESTIMONIAL",
    label: "Testimonial Card",
    description: "User quote and avatar for social proof",
    icon: Quote,
    color: "from-amber-500/20 to-orange-600/10 border-amber-500/30",
    defaults: {
      type: "TESTIMONIAL",
      title: "This platform changed my creative workflow forever.",
      subtitle: "â€” James Wilson, Enterprise User â­â­â­â­â­",
      mediaUrl: "https://picsum.photos/seed/avatar/80/80",
      isVideo: false,
    },
  },
];

const BLOCK_TYPE_META: Record<
  BlockType,
  { icon: React.ElementType; color: string; label: string }
> = {
  HERO: { icon: Sparkles, color: "text-violet-400", label: "Hero" },
  FEATURE_CARD: { icon: LayoutTemplate, color: "text-blue-400", label: "Feature" },
  DISCOVER_GRID: { icon: Grid3x3, color: "text-emerald-400", label: "Discover" },
  TESTIMONIAL: { icon: Quote, color: "text-amber-400", label: "Testimonial" },
};

type EditablePageId =
  | "home"
  | "discover"
  | "character"
  | "moodboard"
  | "original-series"
  | "apps"
  | "apps-tool-transitions"
  | "beauty2";

type EditablePageMeta = {
  id: EditablePageId;
  label: string;
  route: string;
  runtimeConnected: boolean;
  note?: string;
  defaultHeroTitle: string;
  defaultHeroSubtitle: string;
  defaultHeroMedia: string;
};

const PAGE_OPTIONS: EditablePageMeta[] = [
  {
    id: "home",
    label: "Home Page",
    route: "/",
    runtimeConnected: true,
    defaultHeroTitle: "The Ultimate AI Creative Studio",
    defaultHeroSubtitle: "Generate breathtaking videos, images and audio in one platform.",
    defaultHeroMedia: "https://picsum.photos/seed/homebuilder/1280/600",
  },
  {
    id: "discover",
    label: "Discover Page",
    route: "/dash",
    runtimeConnected: true,
    defaultHeroTitle: "Discover Community Creations",
    defaultHeroSubtitle: "Browse thousands of AI-generated artworks from our community.",
    defaultHeroMedia: "https://picsum.photos/seed/discoverbuilder/1280/600",
  },
  {
    id: "character",
    label: "Character Page",
    route: "/character",
    runtimeConnected: true,
    defaultHeroTitle: "Make Your Own Character",
    defaultHeroSubtitle: "Upload photos, train your character and use it across tools.",
    defaultHeroMedia: "https://picsum.photos/seed/characterbuilder/1280/600",
  },
  {
    id: "moodboard",
    label: "Moodboard Page",
    route: "/moodboard",
    runtimeConnected: true,
    defaultHeroTitle: "Create Your Moodboard",
    defaultHeroSubtitle: "Pick style presets and build visual direction in seconds.",
    defaultHeroMedia: "https://picsum.photos/seed/moodboardbuilder/1280/600",
  },
  {
    id: "original-series",
    label: "Original Series Page",
    route: "/original-series",
    runtimeConnected: true,
    defaultHeroTitle: "AI-Generated Episodic Content",
    defaultHeroSubtitle: "Launch and manage cinematic AI series with your own style.",
    defaultHeroMedia: "https://picsum.photos/seed/originalseriesbuilder/1280/600",
  },
  {
    id: "apps",
    label: "Apps Page",
    route: "/apps",
    runtimeConnected: true,
    defaultHeroTitle: "SAAD STUDIO Apps",
    defaultHeroSubtitle: "Browse all AI tools in one place.",
    defaultHeroMedia: "https://picsum.photos/seed/appsbuilder/1280/600",
  },
  {
    id: "apps-tool-transitions",
    label: "Transitions Tool Page",
    route: "/apps/tool/transitions",
    runtimeConnected: true,
    defaultHeroTitle: "Transitions Studio",
    defaultHeroSubtitle: "Create transition effects between scenes and frames.",
    defaultHeroMedia: "https://picsum.photos/seed/transitionsbuilder/1280/600",
  },
  {
    id: "beauty2",
    label: "Beauty Studio Page",
    route: "/beauty2.html",
    runtimeConnected: true,
    defaultHeroTitle: "Beauty and Model Studio",
    defaultHeroSubtitle: "Choose style tools and generate beauty results.",
    defaultHeroMedia: "https://picsum.photos/seed/beautybuilder/1280/600",
  },
];

// â”€â”€â”€ UNIQUE ID HELPER â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

let _counter = 0;
function uid() {
  return `block-${Date.now()}-${_counter++}`;
}

function getYouTubeId(url: string): string | null {
  if (!url) return null;
  try {
    const u = new URL(url);
    if (u.hostname.includes("youtu.be")) return u.pathname.slice(1).split("?")[0] || null;
    if (u.hostname.includes("youtube.com")) {
      if (u.pathname.includes("/embed/")) return u.pathname.split("/embed/")[1]?.split("?")[0] || null;
      return u.searchParams.get("v");
    }
    return null;
  } catch {
    const m = url.match(/(?:v=|youtu\.be\/)([a-zA-Z0-9_-]{11})/);
    return m ? m[1] : null;
  }
}

function defaultBlocksForPage(page: EditablePageMeta): LayoutBlock[] {
  const hero: LayoutBlock = {
    id: uid(),
    type: "HERO",
    title: page.defaultHeroTitle,
    subtitle: page.defaultHeroSubtitle,
    mediaUrl: page.defaultHeroMedia,
    isVideo: false,
    badge: "LIVE",
  };

  if (page.id === "home") {
    return [
      {
        id: uid(),
        type: "HERO",
        title: "Cinema Studio 3.0",
        subtitle: "Direct cinematic worlds with AI — from concept to final cut in minutes.",
        mediaUrl: "/landing/hero-1.jpg",
        isVideo: false,
        badge: "New Release",
      },
      {
        id: uid(),
        type: "HERO",
        title: "Zephyr Original Series",
        subtitle: "AI-generated episodic content with consistent characters and cinematic audio.",
        mediaUrl: "/landing/hero-2.jpg",
        isVideo: false,
        badge: "Original",
      },
      {
        id: uid(),
        type: "HERO",
        title: "Image Studio 4K",
        subtitle: "19 world-class models. One canvas. Zero limits.",
        mediaUrl: "/landing/hero-3.jpg",
        isVideo: false,
        badge: "Top Choice",
      },
      {
        id: uid(),
        type: "HERO",
        title: "Nano Banana Pro",
        subtitle: "Our fastest, sharpest proprietary image model.",
        mediaUrl: "/landing/hero-4.jpg",
        isVideo: false,
        badge: "Exclusive",
      },
      {
        id: uid(),
        type: "FEATURE_CARD",
        title: "Create Image",
        subtitle: "Generate stunning visuals with 19 AI models",
        mediaUrl: "/landing/tool-create-image.png",
        isVideo: false,
      },
      {
        id: uid(),
        type: "FEATURE_CARD",
        title: "Create Video",
        subtitle: "Text-to-video with 13 production engines",
        mediaUrl: "/landing/tool-create-video.png",
        isVideo: false,
      },
      {
        id: uid(),
        type: "FEATURE_CARD",
        title: "Cinema Studio Video",
        subtitle: "Professional cinematic AI production",
        mediaUrl: "/landing/tool-cinema.png",
        isVideo: false,
      },
      {
        id: uid(),
        type: "FEATURE_CARD",
        title: "AI Influencer",
        subtitle: "Build virtual influencer identities at scale",
        mediaUrl: "/landing/tool-ai-influencer.png",
        isVideo: false,
      },
      {
        id: uid(),
        type: "FEATURE_CARD",
        title: "Soul ID Character",
        subtitle: "Consistent character design across scenes",
        mediaUrl: "/landing/tool-soul-id.png",
        isVideo: false,
      },
      {
        id: uid(),
        type: "DISCOVER_GRID",
        title: "Relight",
        subtitle: "Relight any image with AI precision",
        mediaUrl: "/landing/tool-relight.png",
        isVideo: false,
      },
      {
        id: uid(),
        type: "DISCOVER_GRID",
        title: "Face Swap",
        subtitle: "Swap faces with pixel-perfect accuracy",
        mediaUrl: "/landing/tool-face-swap.png",
        isVideo: false,
      },
      {
        id: uid(),
        type: "DISCOVER_GRID",
        title: "UGC Factory",
        subtitle: "User-generated content simulator",
        mediaUrl: "/landing/tool-ugc-factory.png",
        isVideo: false,
      },
      {
        id: uid(),
        type: "DISCOVER_GRID",
        title: "Video Upscale",
        subtitle: "Enhance resolution to 4K / 8K",
        mediaUrl: "/landing/tool-upscale.png",
        isVideo: false,
      },
      {
        id: uid(),
        type: "DISCOVER_GRID",
        title: "Character Swap",
        subtitle: "Transform any character seamlessly",
        mediaUrl: "/landing/tool-char-swap.png",
        isVideo: false,
      },
      {
        id: uid(),
        type: "DISCOVER_GRID",
        title: "Fashion Factory",
        subtitle: "AI fashion and outfit design studio",
        mediaUrl: "/landing/tool-fashion-factory.png",
        isVideo: false,
      },
    ];
  }

  if (page.id === "discover") {
    return [
      {
        id: uid(),
        type: "HERO",
        title: "Cinema Studio 3.0",
        subtitle: "Director-level control over AI video generation.",
        mediaUrl: "/explore/hero-cinema-studio.jpg",
        isVideo: false,
        badge: "NEW",
      },
      {
        id: uid(),
        type: "FEATURE_CARD",
        title: "Create Image",
        subtitle: "Generate AI images",
        mediaUrl: "/explore/tool-create-image.jpg",
        isVideo: false,
      },
      {
        id: uid(),
        type: "FEATURE_CARD",
        title: "Create Video",
        subtitle: "Generate AI videos",
        mediaUrl: "/explore/tool-create-video.jpg",
        isVideo: false,
      },
      {
        id: uid(),
        type: "FEATURE_CARD",
        title: "Motion Control",
        subtitle: "Precise character control",
        mediaUrl: "/explore/tool-motion-control.jpg",
        isVideo: false,
      },
      {
        id: uid(),
        type: "FEATURE_CARD",
        title: "Soul 2.0",
        subtitle: "Ultra-realistic fashion visuals",
        mediaUrl: "/explore/tool-soul-2.jpg",
        isVideo: false,
      },
      {
        id: uid(),
        type: "DISCOVER_GRID",
        title: "Nano Banana Pro",
        subtitle: "Best 4K image model",
        mediaUrl: "/explore/top-nano-banana-pro.jpg",
        isVideo: false,
      },
      {
        id: uid(),
        type: "DISCOVER_GRID",
        title: "Kling 3.0",
        subtitle: "Cinematic text-to-video",
        mediaUrl: "/explore/top-kling-3.jpg",
        isVideo: false,
      },
      {
        id: uid(),
        type: "DISCOVER_GRID",
        title: "Seedream 5.0",
        subtitle: "Intelligent visual reasoning",
        mediaUrl: "/explore/top-seedream-5.jpg",
        isVideo: false,
      },
    ];
  }

  if (page.id === "moodboard") {
    return [
      hero,
      {
        id: uid(),
        type: "FEATURE_CARD",
        title: "Choose your references",
        subtitle: "Upload style references to build a coherent moodboard.",
        mediaUrl: "https://picsum.photos/seed/moodboard-feature-1/600/400",
        isVideo: false,
      },
      {
        id: uid(),
        type: "FEATURE_CARD",
        title: "AI learns your style",
        subtitle: "Lighting, palette, composition and visual direction.",
        mediaUrl: "https://picsum.photos/seed/moodboard-feature-2/600/400",
        isVideo: false,
      },
    ];
  }

  if (page.id === "original-series") {
    return [
      hero,
      {
        id: uid(),
        type: "FEATURE_CARD",
        title: "Episodic Continuity",
        subtitle: "Characters and style remain consistent across episodes.",
        mediaUrl: "https://picsum.photos/seed/series-feature-1/600/400",
        isVideo: false,
      },
      {
        id: uid(),
        type: "FEATURE_CARD",
        title: "Cinematic Generation",
        subtitle: "Scene-level cinematic output with dynamic lighting.",
        mediaUrl: "https://picsum.photos/seed/series-feature-2/600/400",
        isVideo: false,
      },
      {
        id: uid(),
        type: "DISCOVER_GRID",
        title: "Neon Frontier",
        subtitle: "Sci-Fi series card",
        mediaUrl: "https://picsum.photos/seed/series-grid-1/600/800",
        isVideo: false,
      },
    ];
  }

  if (page.id === "apps") {
    return [
      hero,
      {
        id: uid(),
        type: "DISCOVER_GRID",
        title: "Story AI",
        subtitle: "Creative writing tools",
        mediaUrl: "https://picsum.photos/seed/apps-grid-1/600/800",
        isVideo: false,
      },
      {
        id: uid(),
        type: "DISCOVER_GRID",
        title: "Portrait AI",
        subtitle: "Portrait enhancement tools",
        mediaUrl: "https://picsum.photos/seed/apps-grid-2/600/800",
        isVideo: false,
      },
    ];
  }

  if (page.id === "character" || page.id === "apps-tool-transitions") {
    return [
      hero,
      {
        id: uid(),
        type: "FEATURE_CARD",
        title: page.id === "character" ? "Upload photos to train character" : "Select transition presets",
        subtitle: page.id === "character" ? "Train once, use across scenes." : "Use cinematic preset collections.",
        mediaUrl: "https://picsum.photos/seed/feature-generic/600/400",
        isVideo: false,
      },
    ];
  }

  return [hero];
}

// â”€â”€â”€ BLOCK PREVIEW RENDERER â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

function BlockPreview({ block, compact = false }: { block: LayoutBlock; compact?: boolean }) {
  const meta = BLOCK_TYPE_META[block.type];
  const Icon = meta.icon;

  if (block.type === "HERO") {
    return (
      <div className="relative rounded-xl overflow-hidden bg-slate-900 border border-slate-700" style={{ minHeight: compact ? 80 : 160 }}>
        {block.youtubeUrl && getYouTubeId(block.youtubeUrl) ? (
          <img src={`https://img.youtube.com/vi/${getYouTubeId(block.youtubeUrl)}/hqdefault.jpg`} alt="" className="absolute inset-0 w-full h-full object-cover opacity-50" />
        ) : block.isVideo ? (
          <div className="absolute inset-0 flex items-center justify-center bg-slate-900/80">
            <Play className="w-8 h-8 text-white/60" />
          </div>
        ) : block.mediaUrl ? (
          <img src={block.mediaUrl} alt="" className="absolute inset-0 w-full h-full object-cover opacity-50" />
        ) : null}
        <div className="relative z-10 p-4 flex flex-col justify-end h-full" style={{ minHeight: compact ? 80 : 160 }}>
          {block.badge && (
            <span className="mb-1 inline-flex w-fit px-2 py-0.5 rounded-full text-[9px] font-bold bg-violet-600 text-white">
              {block.badge}
            </span>
          )}
          {!compact && <p className="text-white font-bold text-sm leading-snug">{block.title}</p>}
          {!compact && <p className="text-slate-300 text-xs mt-1 line-clamp-1">{block.subtitle}</p>}
        </div>
        <div className="absolute top-2 right-2">
          <span className={`px-1.5 py-0.5 rounded text-[9px] font-bold bg-slate-900/80 ${meta.color}`}>
            {meta.label}
          </span>
        </div>
      </div>
    );
  }

  if (block.type === "FEATURE_CARD") {
    return (
      <div className="rounded-xl bg-gradient-to-br from-blue-950/60 to-slate-900 border border-blue-800/40 p-4 flex gap-3" style={{ minHeight: compact ? 60 : 90 }}>
        {block.mediaUrl && !compact && (
          <div className="w-16 h-16 rounded-lg overflow-hidden flex-shrink-0 border border-slate-700">
            <img src={block.mediaUrl} alt="" className="w-full h-full object-cover" />
          </div>
        )}
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-1.5 mb-1">
            <Icon className={`w-3.5 h-3.5 flex-shrink-0 ${meta.color}`} />
            <span className={`text-[9px] font-bold uppercase ${meta.color}`}>{meta.label}</span>
          </div>
          <p className="text-white text-xs font-semibold leading-snug">{block.title}</p>
          {!compact && <p className="text-slate-400 text-[11px] mt-0.5 line-clamp-2">{block.subtitle}</p>}
        </div>
      </div>
    );
  }

  if (block.type === "DISCOVER_GRID") {
    return (
      <div className="rounded-xl overflow-hidden relative border border-slate-700 bg-slate-900" style={{ minHeight: compact ? 70 : 120 }}>
        {block.mediaUrl && (
          <img src={block.mediaUrl} alt="" className="w-full h-full object-cover absolute inset-0 opacity-70" style={{ minHeight: compact ? 70 : 120 }} />
        )}
        <div className="absolute inset-0 bg-gradient-to-t from-slate-950/90 to-transparent" />
        <div className="relative z-10 p-3 flex flex-col justify-end h-full" style={{ minHeight: compact ? 70 : 120 }}>
          <span className={`text-[9px] font-bold uppercase mb-0.5 ${meta.color}`}>{meta.label}</span>
          {!compact && <p className="text-white text-xs font-semibold leading-snug">{block.title}</p>}
          {!compact && <p className="text-slate-400 text-[10px] mt-0.5">{block.subtitle}</p>}
        </div>
      </div>
    );
  }

  if (block.type === "TESTIMONIAL") {
    return (
      <div className="rounded-xl bg-gradient-to-br from-amber-950/50 to-slate-900 border border-amber-800/30 p-4 flex gap-3" style={{ minHeight: compact ? 60 : 80 }}>
        {block.mediaUrl && !compact && (
          <div className="w-10 h-10 rounded-full overflow-hidden border border-amber-700/40 flex-shrink-0">
            <img src={block.mediaUrl} alt="" className="w-full h-full object-cover" />
          </div>
        )}
        <div className="min-w-0 flex-1">
          <Quote className={`w-3 h-3 mb-1 ${meta.color}`} />
          <p className="text-slate-200 text-[11px] leading-relaxed italic line-clamp-2">{block.title}</p>
          {!compact && <p className={`text-[10px] mt-1 font-semibold ${meta.color}`}>{block.subtitle}</p>}
        </div>
      </div>
    );
  }

  return null;
}

// â”€â”€â”€ SORTABLE CANVAS BLOCK â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

function SortableBlock({
  block,
  isSelected,
  onSelect,
}: {
  block: LayoutBlock;
  isSelected: boolean;
  onSelect: () => void;
}) {
  const { attributes, listeners, setNodeRef, transform, transition, isDragging } =
    useSortable({ id: block.id });

  const style: React.CSSProperties = {
    transform: CSS.Transform.toString(transform),
    transition,
    opacity: isDragging ? 0.35 : 1,
    zIndex: isDragging ? 0 : undefined,
  };

  return (
    <div ref={setNodeRef} style={style} className="group relative">
      {/* Selection ring */}
      <div
        onClick={onSelect}
        className={`cursor-pointer rounded-xl transition-all duration-200 ${
          isSelected
            ? "ring-2 ring-violet-500 ring-offset-2 ring-offset-slate-950"
            : "ring-1 ring-transparent hover:ring-slate-600"
        }`}
      >
        <BlockPreview block={block} />
      </div>

      {/* Drag handle */}
      <div
        {...attributes}
        {...listeners}
        className="absolute left-2 top-1/2 -translate-y-1/2 opacity-0 group-hover:opacity-100 transition-opacity cursor-grab active:cursor-grabbing z-20"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="bg-slate-900/90 rounded-md p-1 border border-slate-700 shadow-lg">
          <GripVertical className="w-4 h-4 text-slate-400" />
        </div>
      </div>

      {/* Selected indicator */}
      {isSelected && (
        <div className="absolute top-2 left-2 bg-violet-600 text-white text-[9px] px-2 py-0.5 rounded-full font-bold z-20 pointer-events-none">
          SELECTED
        </div>
      )}
    </div>
  );
}

// â”€â”€â”€ DROPPABLE CANVAS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

function DroppableCanvas({ children, isEmpty }: { children: React.ReactNode; isEmpty: boolean }) {
  const { setNodeRef, isOver } = useDroppable({ id: "canvas" });
  return (
    <div
      ref={setNodeRef}
      className={`flex-1 min-h-[500px] rounded-2xl border-2 border-dashed transition-all duration-200 p-3 space-y-3 ${
        isOver
          ? "border-violet-500 bg-violet-500/5"
          : "border-slate-700/60 bg-slate-900/20"
      }`}
    >
      {children}
      {isEmpty && (
        <div className="flex flex-col items-center justify-center py-24 gap-3 text-slate-700 pointer-events-none select-none">
          <Layers className="w-10 h-10" />
          <p className="text-sm font-medium">Drag blocks here to build your layout</p>
          <p className="text-xs">Elements from the left panel will appear here</p>
        </div>
      )}
    </div>
  );
}

// â”€â”€â”€ PALETTE DRAG ITEM â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

function PaletteItem({
  template,
  onAdd,
}: {
  template: (typeof BLOCK_TEMPLATES)[number];
  onAdd: () => void;
}) {
  const Icon = template.icon;
  return (
    <div
      draggable
      onDragStart={(e) => {
        e.dataTransfer.setData("blockType", template.type);
        e.dataTransfer.effectAllowed = "copy";
      }}
      className={`group rounded-xl border bg-gradient-to-br ${template.color} p-3 transition-all hover:scale-[1.02] hover:shadow-lg hover:shadow-black/20 select-none`}
    >
      <div className="flex items-center gap-2.5">
        <div className="w-8 h-8 rounded-lg bg-slate-900/60 flex items-center justify-center flex-shrink-0 border border-slate-700/50">
          <Icon className="w-4 h-4 text-slate-300" />
        </div>
        <div className="min-w-0">
          <p className="text-xs font-bold text-slate-200 leading-tight truncate">{template.label}</p>
          <p className="text-[10px] text-slate-500 leading-tight mt-0.5 line-clamp-1">{template.description}</p>
        </div>
        <GripVertical className="w-3.5 h-3.5 text-slate-600 ml-auto flex-shrink-0 group-hover:text-slate-400 transition-colors cursor-grab active:cursor-grabbing" />
        <button
          type="button"
          onClick={(e) => {
            e.stopPropagation();
            onAdd();
          }}
          className="px-2 py-1 rounded-md text-[10px] font-bold bg-violet-600/80 text-white hover:bg-violet-500 transition-colors"
        >
          + Add
        </button>
      </div>
    </div>
  );
}

// â”€â”€â”€ INLINE EDITOR MODAL â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

function BlockEditor({
  block,
  onSave,
  onDelete,
  onClose,
}: {
  block: LayoutBlock;
  onSave: (updated: LayoutBlock) => void;
  onDelete: () => void;
  onClose: () => void;
}) {
  const [draft, setDraft] = useState<LayoutBlock>({ ...block });
  const fileRef = useRef<HTMLInputElement>(null);

  const [uploading, setUploading] = useState(false);
  const [uploadError, setUploadError] = useState<string | null>(null);

  const handleRealUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setUploadError(null);
    setUploading(true);
    try {
      // Step 1: get a presigned upload URL from the server (uses SERVICE_ROLE_KEY → bypasses RLS)
      const signRes = await fetch("/api/admin/media/upload", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ fileName: file.name, fileType: file.type }),
      });
      if (!signRes.ok) {
        const err = await signRes.json().catch(() => ({}));
        throw new Error(err?.error ?? "Failed to get upload URL");
      }
      const { signedUrl, publicUrl, isVideo } = await signRes.json() as {
        signedUrl: string;
        publicUrl: string;
        isVideo: boolean;
      };

      // Step 2: upload the file directly to Supabase via the presigned URL
      const uploadRes = await fetch(signedUrl, {
        method: "PUT",
        headers: { "Content-Type": file.type },
        body: file,
      });
      if (!uploadRes.ok) throw new Error("Upload failed");

      setDraft((d) => ({ ...d, mediaUrl: publicUrl, isVideo }));
    } catch (error) {
      setUploadError(error instanceof Error ? error.message : "Upload failed");
    } finally {
      setUploading(false);
      e.target.value = "";
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.96, y: 8 }}
      animate={{ opacity: 1, scale: 1, y: 0 }}
      exit={{ opacity: 0, scale: 0.96, y: 8 }}
      transition={{ duration: 0.2 }}
      className="fixed inset-0 z-50 flex items-center justify-center p-4"
      onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}
    >
      {/* Backdrop */}
      <div className="absolute inset-0 bg-slate-950/80 backdrop-blur-sm" onClick={onClose} />

      {/* Panel */}
      <div className="relative z-10 w-full max-w-xl bg-slate-900 border border-slate-700 rounded-2xl shadow-2xl shadow-black/60 overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-4 border-b border-slate-800">
          <div className="flex items-center gap-2.5">
            <div className="w-7 h-7 rounded-lg bg-violet-600/20 border border-violet-500/30 flex items-center justify-center">
              <Pencil className="w-3.5 h-3.5 text-violet-400" />
            </div>
            <div>
              <p className="text-sm font-bold text-white">Edit Block</p>
              <p className="text-[10px] text-slate-500">{BLOCK_TYPE_META[draft.type].label} â€” {draft.id}</p>
            </div>
          </div>
          <button onClick={onClose} className="p-1.5 rounded-lg hover:bg-slate-800 text-slate-500 hover:text-slate-300 transition-colors">
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Body */}
        <div className="p-5 space-y-4 max-h-[70vh] overflow-y-auto">
          {/* Live mini preview */}
          <div className="rounded-xl overflow-hidden border border-slate-700/60">
            <BlockPreview block={draft} />
          </div>

          {/* Title */}
          <div>
            <label className="block text-xs font-semibold text-slate-400 mb-1.5">
              {draft.type === "TESTIMONIAL" ? "Quote Text" : "Title / Headline"}
            </label>
            <input
              value={draft.title}
              onChange={(e) => setDraft((d) => ({ ...d, title: e.target.value }))}
              className="w-full px-3 py-2.5 rounded-lg bg-slate-800 border border-slate-700 text-sm text-slate-200 focus:outline-none focus:border-violet-500 focus:ring-1 focus:ring-violet-500/20 transition-colors"
            />
          </div>

          {/* Subtitle */}
          <div>
            <label className="block text-xs font-semibold text-slate-400 mb-1.5">
              {draft.type === "TESTIMONIAL" ? "Author / Attribution" : "Subtitle / Description"}
            </label>
            <textarea
              value={draft.subtitle}
              onChange={(e) => setDraft((d) => ({ ...d, subtitle: e.target.value }))}
              rows={2}
              className="w-full px-3 py-2.5 rounded-lg bg-slate-800 border border-slate-700 text-sm text-slate-200 focus:outline-none focus:border-violet-500 focus:ring-1 focus:ring-violet-500/20 transition-colors resize-none"
            />
          </div>

          {/* Media */}
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <label className="text-xs font-semibold text-slate-400">Media Asset</label>
              {/* Type toggle */}
              <div className="flex items-center gap-1 p-0.5 rounded-lg bg-slate-800 border border-slate-700">
                <button
                  onClick={() => setDraft((d) => ({ ...d, isVideo: false }))}
                  className={`flex items-center gap-1 px-2.5 py-1 rounded-md text-[11px] font-semibold transition-all ${!draft.isVideo ? "bg-violet-600 text-white" : "text-slate-500 hover:text-slate-300"}`}
                >
                  <ImageIcon className="w-3 h-3" /> Image
                </button>
                <button
                  onClick={() => setDraft((d) => ({ ...d, isVideo: true }))}
                  className={`flex items-center gap-1 px-2.5 py-1 rounded-md text-[11px] font-semibold transition-all ${draft.isVideo ? "bg-violet-600 text-white" : "text-slate-500 hover:text-slate-300"}`}
                >
                  <Video className="w-3 h-3" /> Video
                </button>
              </div>
            </div>

            {/* URL input */}
            <input
              value={draft.mediaUrl}
              onChange={(e) => setDraft((d) => ({ ...d, mediaUrl: e.target.value }))}
              placeholder="https://example.com/media.jpg"
              className="w-full px-3 py-2.5 rounded-lg bg-slate-800 border border-slate-700 text-xs text-slate-200 font-mono focus:outline-none focus:border-violet-500 focus:ring-1 focus:ring-violet-500/20 transition-colors placeholder-slate-600"
            />

            {/* Upload button */}
            <input
              ref={fileRef}
              type="file"
              accept="image/*,video/*"
              className="hidden"
              onChange={handleRealUpload}
            />
            <button
              disabled={uploading}
              onClick={() => fileRef.current?.click()}
              className="w-full flex items-center justify-center gap-2 py-2.5 rounded-lg border-2 border-dashed border-slate-600 hover:border-violet-500 text-slate-500 hover:text-violet-400 text-xs font-semibold transition-all disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <Upload className="w-3.5 h-3.5" />
              {uploading ? "Uploading..." : `Upload ${draft.isVideo ? "Video" : "Image"} from Device`}
            </button>
            {uploadError ? <p className="text-[11px] text-red-400">{uploadError}</p> : null}

            {/* YouTube Background URL */}
            <div>
              <label className="block text-xs font-semibold text-slate-400 mb-1.5 flex items-center gap-1.5">
                <Video className="w-3 h-3 text-red-400" />
                YouTube Background URL (optional)
              </label>
              <input
                value={draft.youtubeUrl ?? ""}
                onChange={(e) => setDraft((d) => ({ ...d, youtubeUrl: e.target.value }))}
                placeholder="https://www.youtube.com/watch?v=..."
                className="w-full px-3 py-2.5 rounded-lg bg-slate-800 border border-slate-700 text-xs text-slate-200 font-mono focus:outline-none focus:border-red-500 focus:ring-1 focus:ring-red-500/20 transition-colors placeholder-slate-600"
              />
              {draft.youtubeUrl && getYouTubeId(draft.youtubeUrl) && (
                <p className="text-[10px] text-emerald-400 mt-1">✓ YouTube ID: {getYouTubeId(draft.youtubeUrl)}</p>
              )}
            </div>
          </div>

          {/* Badge (HERO only) */}
          {draft.type === "HERO" && (
            <div>
              <label className="block text-xs font-semibold text-slate-400 mb-1.5">Badge Label (optional)</label>
              <input
                value={draft.badge ?? ""}
                onChange={(e) => setDraft((d) => ({ ...d, badge: e.target.value }))}
                placeholder="e.g. NEW, BETA, LIVE"
                className="w-full px-3 py-2.5 rounded-lg bg-slate-800 border border-slate-700 text-sm text-slate-200 focus:outline-none focus:border-violet-500 transition-colors placeholder-slate-600"
              />
            </div>
          )}

          {/* HERO-only extra controls */}
          {draft.type === "HERO" && (
            <>
              {/* CTA button */}
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-semibold text-slate-400 mb-1.5">CTA Button Text</label>
                  <input
                    value={draft.ctaLabel ?? ""}
                    onChange={(e) => setDraft((d) => ({ ...d, ctaLabel: e.target.value }))}
                    placeholder="Try Now"
                    className="w-full px-3 py-2.5 rounded-lg bg-slate-800 border border-slate-700 text-sm text-slate-200 focus:outline-none focus:border-violet-500 transition-colors placeholder-slate-600"
                  />
                </div>
                <div>
                  <label className="block text-xs font-semibold text-slate-400 mb-1.5">CTA Button Link</label>
                  <input
                    value={draft.ctaHref ?? ""}
                    onChange={(e) => setDraft((d) => ({ ...d, ctaHref: e.target.value }))}
                    placeholder="/dash"
                    className="w-full px-3 py-2.5 rounded-lg bg-slate-800 border border-slate-700 text-sm text-slate-200 font-mono focus:outline-none focus:border-violet-500 transition-colors placeholder-slate-600"
                  />
                </div>
              </div>

              {/* Trailer URL */}
              <div>
                <label className="block text-xs font-semibold text-slate-400 mb-1.5 flex items-center gap-1.5">
                  <Play className="w-3 h-3 text-red-400" />
                  Watch Trailer URL (YouTube)
                </label>
                <input
                  value={draft.trailerUrl ?? ""}
                  onChange={(e) => setDraft((d) => ({ ...d, trailerUrl: e.target.value }))}
                  placeholder="https://www.youtube.com/watch?v=..."
                  className="w-full px-3 py-2.5 rounded-lg bg-slate-800 border border-slate-700 text-xs text-slate-200 font-mono focus:outline-none focus:border-red-500 focus:ring-1 focus:ring-red-500/20 transition-colors placeholder-slate-600"
                />
                {draft.trailerUrl && getYouTubeId(draft.trailerUrl) && (
                  <p className="text-[10px] text-emerald-400 mt-1">✓ Trailer ready — &quot;Watch Trailer&quot; button will appear on site</p>
                )}
              </div>

              {/* Accent color */}
              <div>
                <label className="block text-xs font-semibold text-slate-400 mb-1.5">Accent Color</label>
                <div className="flex items-center gap-2">
                  <input
                    type="color"
                    value={draft.accentColor ?? "#8b5cf6"}
                    onChange={(e) => setDraft((d) => ({ ...d, accentColor: e.target.value }))}
                    className="h-9 w-14 rounded-lg border border-slate-700 bg-slate-800 cursor-pointer p-0.5"
                  />
                  <input
                    value={draft.accentColor ?? "#8b5cf6"}
                    onChange={(e) => setDraft((d) => ({ ...d, accentColor: e.target.value }))}
                    placeholder="#8b5cf6"
                    className="flex-1 px-3 py-2.5 rounded-lg bg-slate-800 border border-slate-700 text-sm text-slate-200 font-mono focus:outline-none focus:border-violet-500 transition-colors placeholder-slate-600"
                  />
                </div>
              </div>
            </>
          )}
        </div>

        {/* Footer */}
        <div className="flex gap-3 px-5 py-4 border-t border-slate-800 bg-slate-900/80">
          <button
            onClick={() => { onSave(draft); onClose(); }}
            className="flex-1 py-2.5 rounded-xl bg-violet-600 hover:bg-violet-500 text-white text-sm font-bold transition-colors flex items-center justify-center gap-2"
          >
            <CheckCircle2 className="w-4 h-4" /> Apply Changes
          </button>
          <button
            onClick={onDelete}
            className="px-4 py-2.5 rounded-xl bg-red-600/20 border border-red-500/30 text-red-400 text-sm font-bold hover:bg-red-600/30 transition-colors flex items-center gap-2"
          >
            <Trash2 className="w-4 h-4" /> Delete
          </button>
              </div>
            </div>
    </motion.div>
  );
}

// â”€â”€â”€ MAIN PAGE COMPONENT â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

export default function PageBuilderPage() {
  const [activePage, setActivePage] = useState<EditablePageId>("home");
  const [blocks, setBlocks] = useState<LayoutBlock[]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [editingBlock, setEditingBlock] = useState<LayoutBlock | null>(null);
  const [activeId, setActiveId] = useState<string | null>(null);
  const [saved, setSaved] = useState(false);
  const [saving, setSaving] = useState(false);
  const [pageDropdown, setPageDropdown] = useState(false);
  const [previewVersion, setPreviewVersion] = useState(0);
  const canvasRef = useRef<HTMLDivElement>(null);

  const selectedBlock = blocks.find((b) => b.id === selectedId) ?? null;
  const activePageMeta =
    PAGE_OPTIONS.find((p) => p.id === activePage) ?? PAGE_OPTIONS[0];

  // Load layout from API when page changes
  useEffect(() => {
    setBlocks([]);
    setSelectedId(null);
    fetch(`/api/admin/layouts?page=${activePage}`)
      .then((r) => r.json())
      .then((data) => {
        const raw = data.layoutBlocks;
        if (Array.isArray(raw) && raw.length > 0) {
          const parsed = raw as LayoutBlock[];
          const hasLegacyPlaceholder =
            parsed.length === 1 &&
            parsed[0]?.type === "HERO" &&
            typeof parsed[0]?.mediaUrl === "string" &&
            parsed[0].mediaUrl.includes("picsum.photos/seed") &&
            ((parsed[0].title || "").trim().toLowerCase() === activePageMeta.defaultHeroTitle.trim().toLowerCase());

          if (hasLegacyPlaceholder) {
            setBlocks(defaultBlocksForPage(activePageMeta));
          } else {
            setBlocks(parsed);
          }
        } else {
          setBlocks(defaultBlocksForPage(activePageMeta));
        }
      })
      .catch(() => {});
  }, [activePage, activePageMeta]);

  // dnd sensors
  const sensors = useSensors(
    useSensor(PointerSensor, { activationConstraint: { distance: 6 } })
  );

  // Add block from palette (native HTML5 drag)
  const handleCanvasDrop = useCallback(
    (e: React.DragEvent<HTMLDivElement>) => {
      e.preventDefault();
      const type = e.dataTransfer.getData("blockType") as BlockType;
      if (!type) return;
      const tpl = BLOCK_TEMPLATES.find((t) => t.type === type);
      if (!tpl) return;
      const newBlock: LayoutBlock = { ...tpl.defaults, id: uid() };
      setBlocks((prev) => [...prev, newBlock]);
    },
    []
  );

  const handleAddBlock = (type: BlockType) => {
    const tpl = BLOCK_TEMPLATES.find((t) => t.type === type);
    if (!tpl) return;
    const newBlock: LayoutBlock = { ...tpl.defaults, id: uid() };
    setBlocks((prev) => [...prev, newBlock]);
    setSelectedId(newBlock.id);
    setEditingBlock(newBlock);
  };

  // dnd-kit drag handlers (reorder within canvas)
  const handleDragStart = (event: DragStartEvent) => {
    setActiveId(String(event.active.id));
  };

  const handleDragEnd = (event: DragEndEvent) => {
    const { active, over } = event;
    setActiveId(null);
    if (!over) return;
    if (active.id !== over.id) {
      setBlocks((prev) => {
        const oldIdx = prev.findIndex((b) => b.id === active.id);
        const newIdx = prev.findIndex((b) => b.id === over.id);
        return arrayMove(prev, oldIdx, newIdx);
      });
    }
  };

  const handleBlockUpdate = (updated: LayoutBlock) => {
    setBlocks((prev) => prev.map((b) => (b.id === updated.id ? updated : b)));
  };

  const handleBlockDelete = (id: string) => {
    setBlocks((prev) => prev.filter((b) => b.id !== id));
    if (selectedId === id) setSelectedId(null);
    setEditingBlock(null);
  };

  const handlePublish = async () => {
    setSaving(true);
    try {
      await fetch("/api/admin/layouts", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ pageName: activePage, layoutBlocks: blocks }),
      });
      setPreviewVersion((v) => v + 1);
      setSaved(true);
      setTimeout(() => setSaved(false), 3000);
    } finally {
      setSaving(false);
    }
  };

  const activeBlock = blocks.find((b) => b.id === activeId);

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 flex flex-col">

      {/* â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â• TOP ACTION BAR â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â• */}
      <header className="sticky top-0 z-30 border-b border-slate-800/80 bg-slate-950/95 backdrop-blur-sm px-6 py-3 flex items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-violet-600 to-purple-700 flex items-center justify-center shadow-lg shadow-violet-900/50">
            <Layers className="w-4 h-4 text-white" />
          </div>
          <div>
            <h1 className="text-sm font-bold text-white leading-none">Visual Page Builder</h1>
            <p className="text-[10px] text-slate-500 mt-0.5">Drag, drop & publish layouts</p>
          </div>
        </div>

        <div className="flex items-center gap-3">
          {/* Page selector */}
          <div className="relative">
            <button
              onClick={() => setPageDropdown((p) => !p)}
              className="flex items-center gap-2 px-3.5 py-2 rounded-xl bg-slate-800/80 border border-slate-700 text-sm font-semibold text-slate-200 hover:bg-slate-800 transition-colors min-w-[160px] justify-between"
            >
              <Eye className="w-3.5 h-3.5 text-slate-400" />
              <span>{activePageMeta.label}</span>
              <ChevronDown className={`w-3.5 h-3.5 text-slate-400 transition-transform ${pageDropdown ? "rotate-180" : ""}`} />
            </button>
            <AnimatePresence>
              {pageDropdown && (
                <motion.div
                  initial={{ opacity: 0, y: -6 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -6 }}
                  className="absolute top-full mt-1 left-0 w-[260px] bg-slate-900 border border-slate-700 rounded-xl shadow-xl z-50 overflow-hidden"
                >
                  {PAGE_OPTIONS.map((page) => (
                    <button
                      key={page.id}
                      onClick={() => { setActivePage(page.id); setPageDropdown(false); }}
                      className={`w-full text-left px-4 py-2.5 text-sm transition-colors ${
                        activePage === page.id
                          ? "bg-violet-600/20 text-violet-300 font-semibold"
                          : "text-slate-300 hover:bg-slate-800"
                      }`}
                    >
                      <div className="flex flex-col items-start">
                        <span>{page.label}</span>
                        <span className="text-[11px] text-slate-500">{page.route}</span>
                      </div>
                    </button>
                  ))}
                </motion.div>
              )}
            </AnimatePresence>
          </div>

          {/* Block count badge */}
          <div className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-slate-800/60 border border-slate-700 text-xs text-slate-400">
            <Layers className="w-3.5 h-3.5" />
            <span className="font-semibold text-slate-200">{blocks.length}</span> blocks
          </div>

          <a
            href={activePageMeta.route}
            target="_blank"
            rel="noreferrer"
            className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-slate-800/60 border border-slate-700 text-xs text-cyan-300 hover:text-cyan-200 hover:bg-slate-800 transition-colors"
          >
            <Eye className="w-3.5 h-3.5" />
            Open Live Page
          </a>

          <div
            className={`px-3 py-2 rounded-xl border text-[11px] font-semibold ${
              activePageMeta.runtimeConnected
                ? "bg-emerald-500/10 border-emerald-500/30 text-emerald-300"
                : "bg-amber-500/10 border-amber-500/30 text-amber-300"
            }`}
          >
            {activePageMeta.runtimeConnected ? "Connected" : "Not Connected"}
          </div>

          {/* Publish button */}
          <motion.button
            onClick={handlePublish}
            disabled={saving || !activePageMeta.runtimeConnected}
            whileHover={{ scale: 1.03 }}
            whileTap={{ scale: 0.97 }}
            className="flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-bold text-white disabled:opacity-60 disabled:cursor-not-allowed"
            style={{
              background: "linear-gradient(135deg, #7c3aed 0%, #9333ea 60%, #7c3aed 100%)",
              boxShadow: "0 0 24px rgba(124,58,237,0.5), 0 4px 12px rgba(124,58,237,0.3)",
            }}
          >
            {saving ? (
              <><RefreshCw className="w-4 h-4 animate-spin" /> Saving...</>
            ) : saved ? (
              <><CheckCircle2 className="w-4 h-4" /> Published!</>
            ) : (
              <><Save className="w-4 h-4" /> Save Layout & Publish</>
            )}
          </motion.button>

          <a
            href="/admin"
            className="flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-medium text-slate-500 hover:text-slate-300 border border-slate-800 bg-slate-900/50 transition-colors"
          >
            â† Admin
          </a>
        </div>
      </header>

      {/* â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â• MAIN LAYOUT â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â• */}
      <div className="flex flex-1 overflow-hidden">

        {/* â•â•â• LEFT SIDEBAR â€” Elements Panel â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â• */}
        <aside className="w-64 flex-shrink-0 border-r border-slate-800/80 bg-slate-900/30 flex flex-col overflow-y-auto">
          <div className="px-4 py-3 border-b border-slate-800/60 flex items-center gap-2">
            <Plus className="w-4 h-4 text-violet-400" />
            <span className="text-xs font-bold text-white uppercase tracking-wide">Elements Panel</span>
          </div>

          <div className="px-3 py-3 space-y-2 flex-1">
            <p className="text-[10px] text-slate-600 uppercase tracking-widest px-1 mb-3 font-semibold">
              Drag to canvas â†’
            </p>
            {BLOCK_TEMPLATES.map((tpl) => (
              <PaletteItem
                key={tpl.type}
                template={tpl}
                onAdd={() => handleAddBlock(tpl.type)}
              />
            ))}
            <button
              type="button"
              onClick={() => setBlocks(defaultBlocksForPage(activePageMeta))}
              className="w-full mt-2 py-2 rounded-lg border border-slate-700 bg-slate-800/50 text-xs font-semibold text-slate-300 hover:bg-slate-800 transition-colors"
            >
              Load Starter Sections
            </button>
          </div>

          {/* Mini legend */}
          <div className="px-4 py-3 border-t border-slate-800/60 space-y-1.5">
            <p className="text-[10px] text-slate-600 font-semibold uppercase tracking-widest">Actions</p>
            <div className="flex items-center gap-2 text-[10px] text-slate-600">
              <GripVertical className="w-3 h-3" /> Hover a block to drag & reorder
            </div>
            <div className="flex items-center gap-2 text-[10px] text-slate-600">
              <Pencil className="w-3 h-3" /> Click a block to open the editor
            </div>
            <div className="flex items-center gap-2 text-[10px] text-slate-600">
              <Trash2 className="w-3 h-3" /> Delete from inside the editor
            </div>
          </div>
        </aside>

        {/* Right side: real page preview + editable blocks */}
        <main className="flex-1 min-w-0 p-5 overflow-y-auto">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-2 text-xs text-slate-500">
              <Eye className="w-3.5 h-3.5" />
              <span>
                Live Page Preview —{" "}
                <span className="text-slate-300 font-semibold">
                  {activePageMeta.label}
                </span>
              </span>
            </div>
            <button
              onClick={() => setPreviewVersion((v) => v + 1)}
              className="flex items-center gap-1.5 text-xs text-cyan-300 hover:text-cyan-200 transition-colors bg-cyan-500/10 border border-cyan-500/25 px-3 py-1.5 rounded-lg font-semibold"
            >
              <RefreshCw className="w-3 h-3" /> Refresh Preview
            </button>
          </div>

          <div className="rounded-2xl overflow-hidden border border-slate-700/70 bg-slate-900/40 mb-5">
            <iframe
              key={`${activePage}-${previewVersion}`}
              src={`${activePageMeta.route}?builderPreview=1&v=${previewVersion}`}
              className="w-full border-0"
              style={{ height: "70vh", minHeight: 520 }}
              title={`Live preview ${activePageMeta.label}`}
            />
          </div>

          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-2 text-xs text-slate-500">
              <Layers className="w-3.5 h-3.5" />
              <span>
                Editable Blocks —{" "}
                <span className="text-slate-300 font-semibold">
                  {blocks.length}
                </span>
              </span>
            </div>
            {selectedBlock && (
              <button
                onClick={() => {
                  setEditingBlock(selectedBlock);
                }}
                className="flex items-center gap-1.5 text-xs text-violet-400 hover:text-violet-300 transition-colors bg-violet-600/10 border border-violet-500/25 px-3 py-1.5 rounded-lg font-semibold"
              >
                <Pencil className="w-3 h-3" /> Edit Selected Block
              </button>
            )}
          </div>
          <p className="text-[11px] text-slate-500 mb-3">
            These are saved page sections for this route. Click <span className="text-violet-300 font-semibold">Edit</span> to change text, image, or video, then publish.
          </p>

          {blocks.length > 0 && (
            <div className="mb-4 rounded-xl border border-slate-700/70 bg-slate-900/40 overflow-hidden">
              {blocks.map((block, idx) => (
                <div
                  key={`row-${block.id}`}
                  className="flex items-center justify-between gap-3 px-3 py-2 border-b last:border-b-0 border-slate-800/70"
                >
                  <div className="min-w-0">
                    <p className="text-xs text-slate-200 font-semibold truncate">
                      {idx + 1}. {block.title || BLOCK_TYPE_META[block.type].label}
                    </p>
                    <p className="text-[10px] text-slate-500 truncate">
                      {BLOCK_TYPE_META[block.type].label}
                    </p>
                  </div>
                  <div className="flex items-center gap-2">
                    <button
                      type="button"
                      onClick={() => {
                        setSelectedId(block.id);
                        setEditingBlock(block);
                      }}
                      className="px-2.5 py-1 rounded-md text-[10px] font-semibold bg-violet-600/20 border border-violet-500/30 text-violet-300 hover:bg-violet-600/30"
                    >
                      Edit
                    </button>
                    <button
                      type="button"
                      onClick={() => handleBlockDelete(block.id)}
                      className="px-2.5 py-1 rounded-md text-[10px] font-semibold bg-red-600/20 border border-red-500/30 text-red-300 hover:bg-red-600/30"
                    >
                      Delete
                    </button>
                  </div>
                </div>
              ))}
            </div>
          )}

          <DndContext
            sensors={sensors}
            collisionDetection={closestCenter}
            onDragStart={handleDragStart}
            onDragEnd={handleDragEnd}
          >
            <SortableContext items={blocks.map((b) => b.id)} strategy={verticalListSortingStrategy}>
              <div
                ref={canvasRef}
                onDragOver={(e) => e.preventDefault()}
                onDrop={handleCanvasDrop}
              >
                <DroppableCanvas isEmpty={blocks.length === 0}>
                  {blocks.map((block) => (
                    <SortableBlock
                      key={block.id}
                      block={block}
                      isSelected={selectedId === block.id}
                      onSelect={() => {
                        setSelectedId(block.id);
                        setEditingBlock(block);
                      }}
                    />
                  ))}
                </DroppableCanvas>
              </div>
            </SortableContext>

            <DragOverlay dropAnimation={null}>
              {activeBlock ? (
                <div className="opacity-80 rotate-1 shadow-2xl shadow-black/50">
                  <BlockPreview block={activeBlock} compact />
                </div>
              ) : null}
            </DragOverlay>
          </DndContext>

          <div className="mt-4 flex items-center gap-2 text-[11px] text-slate-700 px-1">
            <AlertTriangle className="w-3.5 h-3.5 flex-shrink-0" />
            You are seeing the real page above. Save changes, then refresh preview if needed.
          </div>
          {!activePageMeta.runtimeConnected && (
            <div className="mt-2 text-[11px] text-amber-300 bg-amber-500/10 border border-amber-500/25 rounded-lg px-3 py-2">
              {activePageMeta.note ?? "This page is not connected to runtime layout rendering yet."}
            </div>
          )}
        </main>
      </div>

      {/* â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â• INLINE BLOCK EDITOR MODAL â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â• */}
      <AnimatePresence>
        {editingBlock && (
          <BlockEditor
            key={editingBlock.id}
            block={editingBlock}
            onSave={(updated) => {
              handleBlockUpdate(updated);
              setEditingBlock(null);
              setSelectedId(null);
            }}
            onDelete={() => {
              handleBlockDelete(editingBlock.id);
            }}
            onClose={() => {
              setEditingBlock(null);
              setSelectedId(null);
            }}
          />
        )}
      </AnimatePresence>
    </div>
  );
}





